version: "3.8"

services:
  data_service:
    image: data_service_image
    container_name: data_service
    ports:
      - "5001:5001"

  server:
    image: server_image
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - DATA_SERVICE_ADDRESS=http://data_service:5001/history
    depends_on:
      - data_service

