apiVersion: apps/v1
kind: Deployment
metadata:
  name: data_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data_service
  template:
    metadata:
      labels:
        app: data_service
    spec:
      containers:
      - name: data_service_container
        image: "docker.io/library/data_service_image:v1_01"
        ports:
        - containerPort: 5001

