apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: server_ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: server.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: server_service
            port:
              number: 80

