apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-data-service-app-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: my-data-service-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-data-service-app-service
            port:
              number: 80

